### ISSUE TITLE
Want to have a chat functionality in the group 

### ISSUE THREAD

**Issue by kimm950** [aburd/beats-with-friends#12]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

I think it is gonna be more fun if we can chat in the real-time

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Members can talk in the group by sending messages

**Describe alternatives you've considered**

group messaging feature(I am not really familiar with `firebase/database` but I've used `firebase/firestore` before for a similar feature I guess they are similar?)

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by aburd** [comment]
@kimm950 
I just gave you access to firebase so you should be able to get this feature underway.

> I think it is gonna be more fun if we can chat in the real-time

Agreed!

> Members can talk in the group by sending messages

Since avatars aren't 100% for every user you'll probably have to come up with a default avatar.
Also, please keep the messages for the group in the "groups" portion of the DB. If you want to have chat separated by song, you'll have to key each chat like `groups/chats/{songKey}`, otherwise if there is one big chat for everything, then `groups/chat` is fine (I think the former will be more future proof though). 

> group messaging feature(I am not really familiar with firebase/database but I've used firebase/firestore before for a similar feature I guess they are similar?)

They're pretty similar, firebase/database is better at the *realtime* portion, firebase/firestore is richer in the *queries* portion.
